'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Terminal, Copy, Check, Shield, AlertTriangle } from 'lucide-react';

export default function LocalDoctor() {
    const [os, setOs] = useState<'windows' | 'unix'>('windows');
    const [copied, setCopied] = useState(false);

    // 1. Windows PowerShell 脚本 (只读)
    const scriptWindows = `# ClawKit Doctor - Diagnostic Script
# Runs LOCALLY. Does NOT upload data.
Write-Host "🦞 ClawKit Doctor starting..." -ForegroundColor Cyan

# 1. Check Node.js
try {
    $nodeVer = node -v
    Write-Host "🟢 Node.js found: $nodeVer" -ForegroundColor Green
} catch {
    Write-Host "🔴 Node.js NOT found! Please install Node.js v18+." -ForegroundColor Red
}

# 2. Check OpenClaw Config Dir
$configPath = "$env:USERPROFILE\\.openclaw"
if (Test-Path $configPath) {
    Write-Host "🟢 Config directory exists at: $configPath" -ForegroundColor Green
} else {
    Write-Host "🔴 Config directory missing. Run 'clawhub init' first." -ForegroundColor Red
}

# 3. Network Check (Localhost)
try {
    $conn = Test-NetConnection -ComputerName "localhost" -Port 3000 -InformationLevel Quiet
    if ($conn) { Write-Host "🟢 Local Agent Port (3000) is OPEN." -ForegroundColor Green }
    else { Write-Host "⚪ Port 3000 is free (Agent not running)." -ForegroundColor Gray }
} catch {
    Write-Host "⚪ Network check skipped." -ForegroundColor Gray
}

Write-Host "✅ Diagnosis Complete. Screenshot this if you need help!" -ForegroundColor Cyan
# Generated by getclawkit.com`;

    // 2. Mac/Linux Bash 脚本 (只读)
    const scriptUnix = `# ClawKit Doctor - Diagnostic Script
# Runs LOCALLY. Does NOT upload data.
echo "🦞 ClawKit Doctor starting..."

# 1. Check Node.js
if command -v node &> /dev/null; then
    echo "🟢 Node.js found: $(node -v)"
else
    echo "🔴 Node.js NOT found! Please install Node.js v18+."
fi

# 2. Check Permissions
if [ -w ~/.openclaw ]; then
    echo "🟢 Write permission OK for ~/.openclaw"
else
    echo "🔴 No write permission or directory missing for ~/.openclaw"
fi

# 3. Check Config File
if [ -f ~/.openclaw/clawhub.json ]; then
    echo "🟢 Config file found."
else
    echo "🔴 Config file missing (clawhub.json)."
fi

echo "✅ Diagnosis Complete. Screenshot this if you need help!"
# Generated by getclawkit.com`;

    const activeScript = os === 'windows' ? scriptWindows : scriptUnix;

    const handleCopy = () => {
        navigator.clipboard.writeText(activeScript);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="w-full max-w-4xl mx-auto space-y-8">
            {/* OS Selector */}
            <div className="flex justify-center gap-4">
                <button
                    onClick={() => setOs('windows')}
                    className={`px-6 py-3 rounded-full font-medium transition-all flex items-center gap-2 ${os === 'windows'
                            ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/25 scale-105'
                            : 'bg-zinc-800 text-zinc-400 hover:bg-zinc-700'
                        }`}
                >
                    <svg className="w-5 h-5" viewBox="0 0 88 88" fill="currentColor"><path d="M0 12.402l35.687-4.86.016 34.423-35.67.203L0 12.402zM35.67 49.329l-.016 34.693L0 79.128V49.532l35.67-.203zM43.229 3.208L88 0v41.79l-44.771.18V3.208zM88 49.12v41.65l-44.771-6.198V49.302l44.771-.182z" /></svg>
                    Windows (PowerShell)
                </button>
                <button
                    onClick={() => setOs('unix')}
                    className={`px-6 py-3 rounded-full font-medium transition-all flex items-center gap-2 ${os === 'unix'
                            ? 'bg-purple-600 text-white shadow-lg shadow-purple-500/25 scale-105'
                            : 'bg-zinc-800 text-zinc-400 hover:bg-zinc-700'
                        }`}
                >
                    <Terminal className="w-5 h-5" />
                    macOS / Linux
                </button>
            </div>

            {/* Script Display */}
            <div className="relative group rounded-xl overflow-hidden border border-white/10 bg-[#0d1117]">
                <div className="flex items-center justify-between px-4 py-3 bg-white/5 border-b border-white/5">
                    <div className="flex gap-2">
                        <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50" />
                        <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/50" />
                        <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50" />
                    </div>
                    <div className="text-xs text-zinc-500 font-mono">
                        {os === 'windows' ? 'Step 1: Open PowerShell -> Paste' : 'Step 1: Open Terminal -> Paste'}
                    </div>
                </div>

                <div className="relative">
                    <pre className="p-6 overflow-x-auto text-sm font-mono leading-relaxed text-zinc-300">
                        <code>{activeScript}</code>
                    </pre>

                    {/* Floating Copy Button */}
                    <div className="absolute top-4 right-4">
                        <Button
                            onClick={handleCopy}
                            className={`transition-all duration-300 ${copied ? 'bg-green-500 text-black hover:bg-green-400' : 'bg-white text-black hover:bg-zinc-200'
                                }`}
                        >
                            {copied ? (
                                <>
                                    <Check className="w-4 h-4 mr-2" /> Copied!
                                </>
                            ) : (
                                <>
                                    <Copy className="w-4 h-4 mr-2" /> Copy Script
                                </>
                            )}
                        </Button>
                    </div>
                </div>
            </div>

            {/* Trust Badges */}
            <div className="grid md:grid-cols-3 gap-4 text-center">
                <div className="p-4 rounded-lg bg-zinc-900/50 border border-white/5">
                    <Shield className="w-6 h-6 text-green-500 mx-auto mb-2" />
                    <h3 className="font-bold text-white text-sm">100% Read-Only</h3>
                    <p className="text-xs text-zinc-500 mt-1">Never modifies your system files.</p>
                </div>
                <div className="p-4 rounded-lg bg-zinc-900/50 border border-white/5">
                    <AlertTriangle className="w-6 h-6 text-yellow-500 mx-auto mb-2" />
                    <h3 className="font-bold text-white text-sm">No Data Upload</h3>
                    <p className="text-xs text-zinc-500 mt-1">Logs stay on your screen only.</p>
                </div>
                <div className="p-4 rounded-lg bg-zinc-900/50 border border-white/5">
                    <Terminal className="w-6 h-6 text-blue-500 mx-auto mb-2" />
                    <h3 className="font-bold text-white text-sm">Open Source</h3>
                    <p className="text-xs text-zinc-500 mt-1">What you see is what you run.</p>
                </div>
            </div>
        </div>
    );
}